# Generated by Django 5.2 on 2025-05-05 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=1)),
                ('sexual_orientation', models.CharField(choices=[('HETERO', '이성애'), ('HOMO', '동성애'), ('BI', '양성애'), ('OTHER', '기타')], max_length=10)),
                ('communication_styles', models.JSONField(default=list)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_preference_km', models.IntegerField(default=5)),
                ('photo_urls', models.JSONField(default=list)),
                ('bio', models.TextField(max_length=300)),
                ('keywords', models.JSONField(default=list)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_birthdate', models.DateField()),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('guardian_documents', models.JSONField(default=dict)),
                ('guardian_agreement', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
