# Generated by Django 5.2 on 2025-05-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_birthYMD',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_communication_way',
            new_name='communication_way',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_current_location_lat',
            new_name='current_location_lat',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_current_location_lon',
            new_name='current_location_lon',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_match_distance',
            new_name='match_distance',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_protector_info_birth_date',
            new_name='protector_info_birth_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_protector_info_name',
            new_name='protector_info_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_protector_info_phone',
            new_name='protector_info_phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_protector_info_relationship',
            new_name='protector_info_relationship',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='_gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='_sex_orientation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferred_orientation',
        ),
        migrations.AddField(
            model_name='profile',
            name='my_gender',
            field=models.CharField(blank=True, choices=[('남자', '남자'), ('여자', '여자')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('남자', '남자'), ('여자', '여자'), ('모두', '모두')], max_length=10, null=True),
        ),
    ]
