# Generated by Django 5.2 on 2025-05-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_approved_profile_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='disability_certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='family_certificate_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
