# Generated by Django 5.2 on 2025-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_guardian_disability_certificate_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='source',
            field=models.CharField(choices=[('gpt', 'GPT'), ('manual', 'Manual')], max_length=10),
        ),
    ]
