# Generated by Django 5.2 on 2025-05-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_autoclosemessage_interestcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthdate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='distance_preference_km',
            new_name='match_distance_km',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='guardian_relationship',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guardian_agreement',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guardian_birthdate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guardian_documents',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo_urls',
        ),
        migrations.AlterField(
            model_name='profile',
            name='communication_styles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexual_orientation',
            field=models.CharField(max_length=20),
        ),
    ]
