# Generated by Django 5.2 on 2025-05-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_chatroom_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('other', '기타')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_orientation',
            field=models.CharField(blank=True, choices=[('heterosexual', '이성애자'), ('homosexual', '동성애자'), ('bisexual', '양성애자')], max_length=20, null=True),
        ),
    ]
