# Generated by Django 5.2.1 on 2025-05-14 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_birth_date_profile__birthymd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_profile_set',
        ),
        migrations.AddField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
