# Generated by Django 5.2.1 on 2025-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_birth_date_profile__birthymd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='disability_certificate_url',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='family_certificate_url',
        ),
        migrations.AddField(
            model_name='guardian',
            name='disability_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/disability/'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='family_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/family/'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='relation',
            field=models.CharField(choices=[('아빠', '아빠'), ('엄마', '엄마'), ('형제자매', '형제자매')], max_length=30),
        ),
    ]
