# Generated by Django 5.2.1 on 2025-05-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_guardian_disability_certificate_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='is_visible',
        ),
    ]
