# Generated by Django 5.2 on 2025-05-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_birthdate_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='guardian_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_name',
            field=models.CharField(default='홍길동', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_phone',
            field=models.CharField(default='010-0000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='guardian_relationship',
            field=models.CharField(default='보호자', max_length=50),
        ),
    ]
