# Generated by Django 5.2 on 2025-05-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_guardian_birth_date_profile_guardian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='communication_styles',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
