# Generated by Django 5.2 on 2025-05-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='_birthYMD',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='communication_styles',
            new_name='_communication_way',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='latitude',
            new_name='_current_location_lat',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='longitude',
            new_name='_current_location_lon',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='_gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='match_distance_km',
            new_name='_match_distance',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='guardian_birth_date',
            new_name='_protector_info_birth_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='guardian_name',
            new_name='_protector_info_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='guardian_phone',
            new_name='_protector_info_phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='guardian_relationship',
            new_name='_protector_info_relationship',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='sexual_orientation',
            new_name='_sex_orientation',
        ),
    ]
