services:
  web:
    build: ./backend
    container_name: django_app
    command: >
      sh -c "
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
      - ./backend/config/credentials:/app/config/credentials
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data:
