# Generated by Django 5.2 on 2025-05-31 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0005_alter_chatroom_chatroom'),
        ('users', '0003_delete_interest_alter_profile_interests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='users.guardian')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
