# Generated by Django 5.2 on 2025-05-30 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interestkeywordcategorymap',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest.interestcategory'),
        ),
        migrations.AddField(
            model_name='interestkeywordcategorymap',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest.interest'),
        ),
        migrations.AddField(
            model_name='interestkeywordcategorymap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestedinterest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest.interestcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('user', 'keyword')},
        ),
        migrations.AlterUniqueTogether(
            name='interestkeywordcategorymap',
            unique_together={('user', 'interest', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='suggestedinterest',
            unique_together={('keyword', 'category')},
        ),
    ]
