# Generated by Django 5.2 on 2025-05-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCloseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='자동 종료 안내 메시지')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 메시지 여부')),
            ],
        ),
        migrations.CreateModel(
            name='BadWordsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_word', models.CharField(max_length=100)),
                ('filtered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_msg', models.TextField()),
                ('filtered_msg', models.TextField(blank=True, null=True)),
                ('msg_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('format_filtered', models.BooleanField(default=False)),
                ('gpt_filtered', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
