# Generated by Django 5.2 on 2025-05-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
