version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "
      python manage.py migrate &&
      daphne -b 0.0.0.0 -p 8000 config.asgi:application
      "
    volumes:
      - .:/app                  # ✅ 현재 backend 폴더가 그대로 /app 에 매핑됨
      - ./media:/app/media     # ✅ 미디어 저장소 유지
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
