FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV TZ=Asia/Seoul

# ✅ 여기서부터 /app/backend 기준으로 설정
WORKDIR /app/backend

# ✅ 모든 코드 복사 후
COPY . /app/backend

# ✅ 의존성 설치
RUN apt-get update && apt-get install -y \
    tzdata \
    netcat-openbsd \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "config.asgi:application"]
