# Generated by Django 5.2 on 2025-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
