# Generated by Django 5.2.1 on 2025-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='format_filtered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='gpt_filtered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
