# Generated by Django 5.2 on 2025-05-31 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='chatroom',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
