# Generated by Django 5.2 on 2025-05-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='firebase_url',
        ),
    ]
