# Generated by Django 5.2 on 2025-05-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_user1', models.CharField(choices=[('pending', '대기 중'), ('accepted', '수락'), ('rejected', '거절')], default='pending', max_length=10)),
                ('status_user2', models.CharField(choices=[('pending', '대기 중'), ('accepted', '수락'), ('rejected', '거절')], default='pending', max_length=10)),
                ('matched_keywords', models.JSONField()),
                ('is_matched', models.BooleanField(default=False)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
