# Generated by Django 5.2 on 2025-06-07 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_initial'),
        ('users', '0003_delete_interest_alter_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.profile'),
        ),
    ]
