# Generated by Django 5.2 on 2025-05-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0004_alter_interestkeywordcategorymap_user'),
        ('users', '0002_rename__birthymd_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='interest.interest'),
        ),
    ]
